version: "3.9"
services:
    postgres:
        image: postgres:14.7
        container_name: 'short-link-service-postgres-container'
        environment:
            POSTGRES_DB: "short-link-service"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        ports:
            - "5432:5432"